services:
  url-shortener:
    build: .
    image: kelbri/url-shortener:latest
    ports:
      - "8082:8082"
    environment:
      - CONFIG_PATH=./config/prod.yaml
    env_file:
      - .env
    volumes:
      - ./config:/config