env: "local"
storage_path: "./storage/storage.db"
http_server:
  address: "localhost:8082"
  timeout: 4s
  idle_timeout: 60s
  user: "user"
  password: "password"
client:
  sso:
    address: "localhost:44044"
    timeout: 5s
    retriesCount: 3