env: "prod"
storage_path: "./storage.db"
http_server:
  address: "0.0.0.0:8082"
  timeout: 4s
  idle_timeout: 30s
  user: "gabr"
client:
  sso:
    address: "localhost:44044"
    timeout: 5s
    retriesCount: 3