name: Deploy to Production

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Install Docker Compose
        run: |
          sudo apt-get install -y docker-compose

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Setup environment variables
        run: |
          echo APP_SECRET=${{ secrets.APP_SECRET }} >> .env
          echo HTTP_SERVER_PASSWORD=${{ secrets.HTTP_SERVER_PASSWORD }} >> .env

      - name: Build and push Docker image
        run: |
          docker-compose build
          docker-compose push

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.DEPLOY_SSH_KEY }}

      - name: Disable strict host key checking
        run: |
          echo -e "Host 89.169.167.200\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config

      - name: Copy docker-compose.yaml to remote server
        run: |
          scp docker-compose.yaml gabr@89.169.167.200:/apps/url-shortener

      - name: Deploy
        run: |
          ssh -o StrictHostKeyChecking=no gabr@89.169.167.200 << EOF
          docker-compose down
          docker pull kelbri/url-shortener:latest
          docker-compose up -d
          EOF
